name: publish

on:
    push:
        branches:
            - master

jobs:
    npm-publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  persist-credentials: false
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'yarn'

            - name: Install
              run: |
                  yarn install --immutable

            - name: publish
              run: npx semantic-release
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
